// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasources: {
    db: {
      url: process.env["DATABASE_URL"] || "postgresql://tradinguser:TradingP@ss2026!Secure@localhost:5432/tradingdb",
    },
  },
});
